version: '3'
services:

    prometheus:
        image: prom/prometheus:v2.2.1
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - $PWD:/etc/prometheus/           

    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        ports:
          - '9100:9100'

    grafana:
        image: grafana/grafana:5.1.3
        container_name: grafana
        ports:
          - "3000:3000"

    cadvisor:
        image: google/cadvisor:v0.29.0
        container_name: cadvisor
        ports:
            - "8095:8080"
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro

    alertmanager:
        image: prom/alertmanager:v0.14.0
        container_name: alertmanager        
        depends_on: 
          - "ping"
        ports:
          - 9093:9093
        volumes:
          - $PWD:/etc/alertmanager/

    mailslurper:
        image: marcopas/docker-mailslurper
        container_name: mailslurper        
        ports:
          - 2500:2500
          - 9000:8080
          - 8085:8085
        volumes:
          - $PWD/mailslurper-config.json:/opt/mailslurper/config.json

    ping:
        image: alpine
        container_name: ping
        command: ping localhost
